language:
  go:
    - "1.11"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  go get -t ./...

script:
  - go test -race -coverprofile c.out

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT